force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Billing</label>
    <nameField>
        <label>Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>closed won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Line__c/Billing_Line__c.object-meta.xml
<CustomObject>
    <label>Billing Line</label>
    <nameField>
        <label>Billing Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Line__c/fields/Billing__c.field-meta.xml
<CustomField>
    <fullName>Billing__c</fullName>
    <label>Billing</label>
    <referenceTo>Billing__c</referenceTo>
    <relationshipLabel>Billing Lines</relationshipLabel>
    <relationshipName>Billing_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/mycontrollerextension.cls
Public class mycontrollerextension{

public List<OpportunityLineItem> oppProductList{get;set;}
String oppID;

    private opportunity opp ;
    public myControllerExtension(ApexPages.StandardController stdController){
    opp = [select id , name , stageName , CloseDate from Opportunity where id =:stdController.getID()] ;
    
    oppId=stdController.getId();
    system.debug('-----------------OppId------------:' +oppId);
    oppProductList=new List<OpportunityLineItem>();
     
    }
    public pageReference createBilling(){
    Billing__c b = new Billing__c();
    b.Opportunity_Name__c = opp.Name;
    b.Date__c = opp.CloseDate;
    b.Stage__c = opp.StageName;
    insert b; 
    
    
   oppProductList=[Select id,OpportunityId , Product2Id ,Quantity , UnitPrice , ServiceDate, ProductCode from OpportunityLineItem where OpportunityId =:oppId];
   system.debug('---------------OppProductList-------- : ' +oppProductList );
   for( OpportunityLineItem opp :oppProductList){
           Billing_Line__c a = new Billing_Line__c();
           a.Billing__c = b.Id;
           a.Date__c = opp.ServiceDate ;
           a.Number__c = opp.Quantity;
           a.Price__c =  opp.UnitPrice;
           a.Product__c = opp.ProductCode;
           insert a;
   }
   
    return new PageReference('/'+b.ID);
        
    }    
    
    
  }