force-app/main/default/objects/Account/fields/Rollup_Amount__c.field-meta.xml
<CustomField>
    <fullName>Rollup_Amount__c</fullName>
    <label>Rollup_Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rollup_Amount_X__c.field-meta.xml
<CustomField>
    <fullName>Rollup_Amount_X__c</fullName>
    <label>Rollup_Amount_X</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rollup_Amount_Y__c.field-meta.xml
<CustomField>
    <fullName>Rollup_Amount_Y__c</fullName>
    <label>Rollup_Amount_Y</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount_X__c.field-meta.xml
<CustomField>
    <fullName>Amount_X__c</fullName>
    <label>Amount_X</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount_Y__c.field-meta.xml
<CustomField>
    <fullName>Amount_Y__c</fullName>
    <label>Amount_Y</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status_Amt__c.field-meta.xml
<CustomField>
    <fullName>Status_Amt__c</fullName>
    <label>Status_Amt</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/accAmountHandlerController.cls
public class accAmountHandlerController {

    public static void onAfterInsert(List<Contact> conList) {
        set<Id> accIds = new set<Id>();
        for(contact con : conList){
            accIds.add(con.accountId);
        }  
        
        if (accIds.size() > 0) {

            Map<id,Account> Accounts = new Map<id,Account>([SELECT id FROM Account WHERE id =: accIds]);
            for (Account acc : Accounts.values()){
                acc.Rollup_Amount_X__c = 0;
                acc.Rollup_Amount_Y__c = 0;
                acc.Rollup_Amount__c = 0;
            } 
            
            for (Contact con : [SELECT id, Amount_X__c , Amount_Y__c , Status_Amt__c, AccountId FROM Contact WHERE AccountId =: accIds]){
                Account acc = Accounts.get(con.AccountId);
                if(con.Amount_X__c != null && con.Status_Amt__c == 'Positive' ){
                    acc.Rollup_Amount_X__c += con.Amount_X__c;
                }else if(con.Amount_Y__c != null && con.Status_Amt__c == 'Negative' ){
                    acc.Rollup_Amount_Y__c += con.Amount_Y__c ;
                }
               acc.Rollup_Amount__c = acc.Rollup_Amount_X__c + acc.Rollup_Amount_Y__c ;
            }    
            
            update Accounts.values();
        
        }
    }    
    
    public static void onAfterUpdate(List<Contact> conList) {
        system.debug('-----conList ----- ' +conList);
     //   system.debug('-----conMap------- ' +conMap);
        
        set<Id> accIds = new set<Id>();
        for(contact con : conList){
            accIds.add(con.accountId);
            system.debug('-----acc IDs ---- ' +accIds);
        }  
        
        if (accIds.size() > 0) {
            
            Map<id,Account> Accounts = new Map<id,Account>([SELECT id FROM Account WHERE id =: accIds]);
            for (Account acc : Accounts.values()){
                acc.Rollup_Amount_X__c = 0;
                acc.Rollup_Amount_Y__c = 0;
                acc.Rollup_Amount__c = 0;
            } 
            
            for (Contact con : [SELECT id, Amount_X__c , Amount_Y__c , Status_Amt__c, AccountId FROM Contact WHERE AccountId =: accIds]){
                Account acc = Accounts.get(con.AccountId);
                if(con.Amount_X__c != null && con.Status_Amt__c == 'Positive' ){
                    acc.Rollup_Amount_X__c += con.Amount_X__c;
                }else if(con.Amount_Y__c != null && con.Status_Amt__c == 'Negative' ){
                    acc.Rollup_Amount_Y__c += con.Amount_Y__c ;
                }
               acc.Rollup_Amount__c = acc.Rollup_Amount_X__c + acc.Rollup_Amount_Y__c ;
            }    
            
            update Accounts.values();
        
        }
    }    
}