force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Member__c/fields/E_Mail_Id__c.field-meta.xml
<CustomField>
    <fullName>E_Mail_Id__c</fullName>
    <label>E_Mail_Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/MemberPopup.cls
public class MemberPopup 
{
    public List<Member__c> memberList {get;set;}
    public List<Member__c> memberAddList {get;set;}
    public String memberName {get;set;}
    public Integer rowNum{get;set;}
    
    public MemberPopup()
    {
        String sql = 'SELECT Name, E_Mail_Id__c FROM Member__c';
        memberList = Database.Query(sql);
        memberAddList = new List<Member__c>();
        memberAddList.add(new Member__c());
    }
        
    public void AddRow()
    {
        memberAddList.add(new Member__c());
    }
    
    public void delRow()
    {
        rowNum = Integer.valueOf(apexpages.currentpage().getparameters().get('index'));
        memberAddList.remove(rowNum);   
    }    
    
    public void saveMemb()
    {
        insert memberAddList;
    }
}