force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <label>Goal</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/showGoalsANDtasks.cls
Public class showGoalsANDtasks{
    public set<ID> goalIDs = new set<ID>();
    public List<task> taskList {get;set;} 
    
    public showGoalsANDtasks(){
        List<Goal__c> goalList = [Select Id, Name, Status__c From Goal__c];
        system.debug('----List data------' +goalList);
        set<Id> goalIDs = new set<Id>();
        for(Goal__c g : goalList){
            goalIDs.add(g.Id);
        }
        system.debug('------set data---- ' +goalIDs);
        taskList = [Select ID , Priority , goal__r.Id , goal__r.Name , Activitydate from Task where goal__r.Id In: goalIDs];
        system.debug('========task === ' +taskList);   
    }     
        
        
}