force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/OpportunityName__c.field-meta.xml
<CustomField>
    <fullName>OpportunityName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/createPaymentRechandlercontroller.cls
public class createPaymentRechandlercontroller{

    public static void onAfterInsert(List<opportunity> oppList) {
        system.debug('-------OppList---- ' +oppList);
        List<payment__c> payList = new List<payment__c>();
        system.debug('------oppList---- ' +oppList);
        for(Opportunity opp : oppList){
            if(opp.StageName == 'Closed Won'){
                payment__c pay = new payment__c();
                pay.Name = opp.Name;
                pay.Amount__c = opp.Amount;
                pay.Date__c = opp.CloseDate;
                pay.OpportunityName__c = opp.Id;
                payList.add(pay);    
            }
        }
        insert payList;
    }

    public static void onAfterUpdate(Map<Id,opportunity> OldMap, Map<Id,opportunity> NewMap) {
        List<payment__c> payList = new List<payment__c>();
        Map<Id,payment__c> payMap = new Map<Id,payment__c>();
        
        for(Opportunity opp : NewMap.values()){
            if(opp.StageName == 'Closed Won' && Oldmap.get(opp.Id).StageName != Newmap.get(opp.Id).StageName){
                payment__c pay = new payment__c();
                pay.Name = opp.Name;
                pay.Amount__c = opp.Amount;
                pay.Date__c = opp.CloseDate;
                pay.OpportunityName__c = opp.Id;
                payList.add(pay);    
            }else{
                payMap = new Map<Id,payment__c>([select Id from payment__c where opportunityName__r.Id =: opp.Id]);
                for(ID payId : payMap.keyset()){
                    payMap.get(payId).Name = Newmap.get(opp.Id).Name; 
                    payMap.get(payId).Amount__c = Newmap.get(opp.Id).Amount;   
                    payMap.get(payId).Date__c = Newmap.get(opp.Id).CloseDate;    
                }
                
            }
        }
        upsert payList; 
        update payMap.values(); 
    }
    
}